///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using www.w3.org.time;  
namespace www.w3.org.time
{
    [Class("http://www.w3.org/2006/time#DateTimeDescription")]
    public interface IDateTimeDescription  : IGeneralDateTimeDescription
    {
	  [Property("http://www.w3.org/2006/time#month")]
	  DateTime Month { get; set; }
			
	  [Property("http://www.w3.org/2006/time#day")]
	  DateTime Day { get; set; }
			
	  [Property("http://www.w3.org/2006/time#year")]
	  DateTime Year { get; set; }
			
	}
}