///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using www.w3.org.time;  
namespace www.w3.org.time
{
    [Class("http://www.w3.org/2006/time#DurationDescription")]
    public interface IDurationDescription  : IGeneralDurationDescription
    {
	  [Property("http://www.w3.org/2006/time#hours")]
	  Decimal Hours { get; set; }
			
	  [Property("http://www.w3.org/2006/time#minutes")]
	  Decimal Minutes { get; set; }
			
	  [Property("http://www.w3.org/2006/time#weeks")]
	  Decimal Weeks { get; set; }
			
	  [Property("http://www.w3.org/2006/time#seconds")]
	  Decimal Seconds { get; set; }
			
	  [Property("http://www.w3.org/2006/time#months")]
	  Decimal Months { get; set; }
			
	  [Property("http://www.w3.org/2006/time#years")]
	  Decimal Years { get; set; }
			
	  [Property("http://www.w3.org/2006/time#days")]
	  Decimal Days { get; set; }
			
	}
}