///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using www.w3.org.time;  
using www.w3.org.owl;  
namespace www.w3.org.time
{
    [Class("http://www.w3.org/2006/time#GeneralDateTimeDescription")]
    public interface IGeneralDateTimeDescription  : ITemporalPosition
    {
	  ///<summary> function AddMonthofyear_Max_1Thing</summary>  
	  ///<param name="IThing"></param>
      [Collection("http://www.w3.org/2006/time#monthOfYear")]
	  ICollection<IThing> AddMonthofyear_Max_1Thing { get; set; }
	
	  ///<summary> function AddUnittype_Exactly_1Thing</summary>  
	  ///<param name="IThing"></param>
      [Collection("http://www.w3.org/2006/time#unitType")]
	  ICollection<IThing> AddUnittype_Exactly_1Thing { get; set; }
	
	  ///<summary> function AddTimezone_Max_1Thing</summary>  
	  ///<param name="IThing"></param>
      [Collection("http://www.w3.org/2006/time#timeZone")]
	  ICollection<IThing> AddTimezone_Max_1Thing { get; set; }
	
	  ///<summary> function AddDayofweek_Max_1Thing</summary>  
	  ///<param name="IThing"></param>
      [Collection("http://www.w3.org/2006/time#dayOfWeek")]
	  ICollection<IThing> AddDayofweek_Max_1Thing { get; set; }
	
	  [Property("http://www.w3.org/2006/time#day")]
	  String Day { get; set; }
			
	  [Property("http://www.w3.org/2006/time#dayOfYear")]
	  String Dayofyear { get; set; }
			
	  [Property("http://www.w3.org/2006/time#hour")]
	  String Hour { get; set; }
			
	  [Property("http://www.w3.org/2006/time#week")]
	  String Week { get; set; }
			
	  [Property("http://www.w3.org/2006/time#month")]
	  String Month { get; set; }
			
	  [Property("http://www.w3.org/2006/time#minute")]
	  String Minute { get; set; }
			
	  [Property("http://www.w3.org/2006/time#year")]
	  String Year { get; set; }
			
	  [Property("http://www.w3.org/2006/time#second")]
	  String Second { get; set; }
			
	}
}