/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package www.w3.org.XMLSchema;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import www.w3.org.rdf.schema.Literal;
	


public  class dateTimeStamp implements IdateTimeStamp {

	IRI newInstance;
	
	public dateTimeStamp(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("http://www.w3.org/2001/XMLSchema#dateTimeStamp"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	
}
