/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package www.w3.org.XMLSchema;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import www.w3.org.rdf.schema.ILiteral;  


public interface IdateTimeStamp extends ILiteral {


	public IRI iri();
			
	
}
