/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package www.w3.org.time;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import www.w3.org.time.GeneralDurationDescription;
import www.w3.org.time.TemporalDuration;
import www.w3.org.owl.IThing;
	


public  class DurationDescription implements IDurationDescription {

	IRI newInstance;
	
	public DurationDescription(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#DurationDescription"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	public void setHours(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#hours"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setMinutes(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#minutes"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setWeeks(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#weeks"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setSeconds(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#seconds"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setMonths(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#months"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setYears(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#years"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setDays(BigDecimal param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#days"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setSeconds_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#seconds"), GLOBAL.factory.createLiteral(param));
	}
	
	public void setMinutes_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#minutes"), GLOBAL.factory.createLiteral(param));
	}
	
	public void setHours_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#hours"), GLOBAL.factory.createLiteral(param));
	}
	
	public void setMonths_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#months"), GLOBAL.factory.createLiteral(param));
	}
	
	public void setDays_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#days"), GLOBAL.factory.createLiteral(param));
	}
	
	public void setYears_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#years"), GLOBAL.factory.createLiteral(param));
	}
	
	public void setWeeks_String(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#weeks"), GLOBAL.factory.createLiteral(param));
	}
	
	
	
	public void addHastrs_Exactly1(IThing parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#hasTRS"), parameter.iri());
	}
			
}
