/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package www.w3.org.time;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import www.w3.org.owl.IThing;  
import www.w3.org.time.TemporalDuration;
	


public  class GeneralDurationDescription implements IGeneralDurationDescription {

	IRI newInstance;
	
	public GeneralDurationDescription(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#GeneralDurationDescription"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	public void setSeconds(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#seconds"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setMinutes(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#minutes"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setHours(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#hours"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setMonths(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#months"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setDays(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#days"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setYears(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#years"), GLOBAL.factory.createLiteral(param));
	}
			
	public void setWeeks(String param)
	{
	 GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#weeks"), GLOBAL.factory.createLiteral(param));
	}
			
	
	public void addHastrs_Exactly1(IThing parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#hasTRS"), parameter.iri());
	}
	
}
