/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package www.w3.org.time;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import www.w3.org.time.ITemporalDuration;  
import www.w3.org.owl.IThing;  


public interface IDuration extends ITemporalDuration {


	public IRI iri();
			
	public void addUnittype_Exactly1(IThing parameter);
			
	
}
