/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package www.w3.org.time;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import www.w3.org.time.ITemporalDuration;  
import w3id.org.saref.IUnitOfMeasure;  


public interface ITemporalUnit extends ITemporalDuration, IUnitOfMeasure {


	public IRI iri();
			
	
}
