/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package www.w3.org.time;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import www.w3.org.time.TemporalPosition;
import www.w3.org.owl.IThing;
	


public  class TimePosition implements ITimePosition {

	IRI newInstance;
	
	public TimePosition(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#TimePosition"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	
	public void addHastrs_Exactly1(IThing parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("http://www.w3.org/2006/time#hasTRS"), parameter.iri());
	}
			
}
