///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#Command")]
    public interface ICommand : IEntity
    {
	  ///<summary> function AddIscommandof_Min_1Function</summary>  
	  ///<param name="IFunction"></param>
      [Collection("https://w3id.org/saref#isCommandOf")]
	  ICollection<IFunction> AddIscommandof_Min_1Function { get; set; }
	
	  ///<summary> function AddActsupon_Only_State</summary>  
	  ///<param name="IState"></param>
      [Collection("https://w3id.org/saref#actsUpon")]
	  ICollection<IState> AddActsupon_Only_State { get; set; }
	
	  [Property("https://w3id.org/saref#hasDescription")]
	  String Hasdescription { get; set; }
			
	}
}