///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#Device")]
    public interface IDevice : IEntity
    {
	  ///<summary> function AddOffers_Only_Service</summary>  
	  ///<param name="IService"></param>
      [Collection("https://w3id.org/saref#offers")]
	  ICollection<IService> AddOffers_Only_Service { get; set; }
	
	  ///<summary> function AddConsistsof_Only_Device</summary>  
	  ///<param name="IDevice"></param>
      [Collection("https://w3id.org/saref#consistsOf")]
	  ICollection<IDevice> AddConsistsof_Only_Device { get; set; }
	
	  ///<summary> function AddMeasuresproperty_Only_Property</summary>  
	  ///<param name="IProperty"></param>
      [Collection("https://w3id.org/saref#measuresProperty")]
	  ICollection<IProperty> AddMeasuresproperty_Only_Property { get; set; }
	
	  ///<summary> function AddHastypicalconsumption_Only_Power</summary>  
	  ///<param name="IPower"></param>
      [Collection("https://w3id.org/saref#hasTypicalConsumption")]
	  ICollection<IPower> AddHastypicalconsumption_Only_Power { get; set; }
	
	  ///<summary> function AddHastypicalconsumption_Only_Energy</summary>  
	  ///<param name="IEnergy"></param>
      [Collection("https://w3id.org/saref#hasTypicalConsumption")]
	  ICollection<IEnergy> AddHastypicalconsumption_Only_Energy { get; set; }
	
	  ///<summary> function AddAccomplishes_Min_1Task</summary>  
	  ///<param name="ITask"></param>
      [Collection("https://w3id.org/saref#accomplishes")]
	  ICollection<ITask> AddAccomplishes_Min_1Task { get; set; }
	
	  ///<summary> function AddControlsproperty_Only_Property</summary>  
	  ///<param name="IProperty"></param>
      [Collection("https://w3id.org/saref#controlsProperty")]
	  ICollection<IProperty> AddControlsproperty_Only_Property { get; set; }
	
	  ///<summary> function AddHasstate_Only_State</summary>  
	  ///<param name="IState"></param>
      [Collection("https://w3id.org/saref#hasState")]
	  ICollection<IState> AddHasstate_Only_State { get; set; }
	
	  ///<summary> function AddMakesmeasurement_Only_Measurement</summary>  
	  ///<param name="IMeasurement"></param>
      [Collection("https://w3id.org/saref#makesMeasurement")]
	  ICollection<IMeasurement> AddMakesmeasurement_Only_Measurement { get; set; }
	
	  ///<summary> function AddIsusedfor_Only_Commodity</summary>  
	  ///<param name="ICommodity"></param>
      [Collection("https://w3id.org/saref#isUsedFor")]
	  ICollection<ICommodity> AddIsusedfor_Only_Commodity { get; set; }
	
	  ///<summary> function AddHasfunction_Min_1Function</summary>  
	  ///<param name="IFunction"></param>
      [Collection("https://w3id.org/saref#hasFunction")]
	  ICollection<IFunction> AddHasfunction_Min_1Function { get; set; }
	
	  ///<summary> function AddHasprofile_Only_Profile</summary>  
	  ///<param name="IProfile"></param>
      [Collection("https://w3id.org/saref#hasProfile")]
	  ICollection<IProfile> AddHasprofile_Only_Profile { get; set; }
	
	  [Property("https://w3id.org/saref#hasDescription")]
	  String Hasdescription { get; set; }
			
	  [Property("https://w3id.org/saref#hasManufacturer")]
	  String Hasmanufacturer { get; set; }
			
	  [Property("https://w3id.org/saref#hasModel")]
	  String Hasmodel { get; set; }
			
	}
}