///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#DoorSwitch")]
    public interface IDoorSwitch  : ISwitch
    {
	  ///<summary> function AddHasfunction_Some_OpenCloseFunction</summary>  
	  ///<param name="IOpenCloseFunction"></param>
      [Collection("https://w3id.org/saref#hasFunction")]
	  ICollection<IOpenCloseFunction> AddHasfunction_Some_OpenCloseFunction { get; set; }
	
	  ///<summary> function AddHasstate_Some_OpenCloseState</summary>  
	  ///<param name="IOpenCloseState"></param>
      [Collection("https://w3id.org/saref#hasState")]
	  ICollection<IOpenCloseState> AddHasstate_Some_OpenCloseState { get; set; }
	
	  ///<summary> function AddConsistsof_Some_Switch</summary>  
	  ///<param name="ISwitch"></param>
      [Collection("https://w3id.org/saref#consistsOf")]
	  ICollection<ISwitch> AddConsistsof_Some_Switch { get; set; }
	
	}
}