///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#EnergyMeter")]
    public interface IEnergyMeter  : IMeter
    {
	  ///<summary> function AddMeasuresproperty_Some_Energy</summary>  
	  ///<param name="IEnergy"></param>
      [Collection("https://w3id.org/saref#measuresProperty")]
	  ICollection<IEnergy> AddMeasuresproperty_Some_Energy { get; set; }
	
	  ///<summary> function AddConsistsof_Some_Meter</summary>  
	  ///<param name="IMeter"></param>
      [Collection("https://w3id.org/saref#consistsOf")]
	  ICollection<IMeter> AddConsistsof_Some_Meter { get; set; }
	
	}
}