///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#LevelControlFunction")]
    public interface ILevelControlFunction  : IActuatingFunction
    {
	  ///<summary> function AddHascommand_Only_StepDownCommand</summary>  
	  ///<param name="IStepDownCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IStepDownCommand> AddHascommand_Only_StepDownCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_SetAbsoluteLevelCommand</summary>  
	  ///<param name="ISetAbsoluteLevelCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<ISetAbsoluteLevelCommand> AddHascommand_Only_SetAbsoluteLevelCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_StepUpCommand</summary>  
	  ///<param name="IStepUpCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IStepUpCommand> AddHascommand_Only_StepUpCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_SetRelativeLevelCommand</summary>  
	  ///<param name="ISetRelativeLevelCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<ISetRelativeLevelCommand> AddHascommand_Only_SetRelativeLevelCommand { get; set; }
	
	}
}