///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#LightSwitch")]
    public interface ILightSwitch  : ISwitch
    {
	  ///<summary> function AddHasfunction_Some_OnOffFunction</summary>  
	  ///<param name="IOnOffFunction"></param>
      [Collection("https://w3id.org/saref#hasFunction")]
	  ICollection<IOnOffFunction> AddHasfunction_Some_OnOffFunction { get; set; }
	
	  ///<summary> function AddConsistsof_Some_Switch</summary>  
	  ///<param name="ISwitch"></param>
      [Collection("https://w3id.org/saref#consistsOf")]
	  ICollection<ISwitch> AddConsistsof_Some_Switch { get; set; }
	
	  ///<summary> function AddHasstate_Some_OnOffState</summary>  
	  ///<param name="IOnOffState"></param>
      [Collection("https://w3id.org/saref#hasState")]
	  ICollection<IOnOffState> AddHasstate_Some_OnOffState { get; set; }
	
	  ///<summary> function AddMeasuresproperty_Some_Light</summary>  
	  ///<param name="ILight"></param>
      [Collection("https://w3id.org/saref#measuresProperty")]
	  ICollection<ILight> AddMeasuresproperty_Some_Light { get; set; }
	
	  ///<summary> function AddOffers_Some_SwitchOnService</summary>  
	  ///<param name="ISwitchOnService"></param>
      [Collection("https://w3id.org/saref#offers")]
	  ICollection<ISwitchOnService> AddOffers_Some_SwitchOnService { get; set; }
	
	}
}