///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#OnOffFunction")]
    public interface IOnOffFunction  : IActuatingFunction
    {
	  ///<summary> function AddHascommand_Only_OffCommand</summary>  
	  ///<param name="IOffCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IOffCommand> AddHascommand_Only_OffCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_OnCommand</summary>  
	  ///<param name="IOnCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IOnCommand> AddHascommand_Only_OnCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_ToggleCommand</summary>  
	  ///<param name="IToggleCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IToggleCommand> AddHascommand_Only_ToggleCommand { get; set; }
	
	}
}