///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#OpenCloseFunction")]
    public interface IOpenCloseFunction  : IActuatingFunction
    {
	  ///<summary> function AddHascommand_Only_CloseCommand</summary>  
	  ///<param name="ICloseCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<ICloseCommand> AddHascommand_Only_CloseCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_OpenCommand</summary>  
	  ///<param name="IOpenCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IOpenCommand> AddHascommand_Only_OpenCommand { get; set; }
	
	}
}