///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#Property")]
    public interface IProperty : IEntity
    {
	  ///<summary> function AddIsmeasuredbydevice_Only_Device</summary>  
	  ///<param name="IDevice"></param>
      [Collection("https://w3id.org/saref#isMeasuredByDevice")]
	  ICollection<IDevice> AddIsmeasuredbydevice_Only_Device { get; set; }
	
	  ///<summary> function AddIscontrolledbydevice_Only_Device</summary>  
	  ///<param name="IDevice"></param>
      [Collection("https://w3id.org/saref#isControlledByDevice")]
	  ICollection<IDevice> AddIscontrolledbydevice_Only_Device { get; set; }
	
	  ///<summary> function AddRelatestomeasurement_Only_Measurement</summary>  
	  ///<param name="IMeasurement"></param>
      [Collection("https://w3id.org/saref#relatesToMeasurement")]
	  ICollection<IMeasurement> AddRelatestomeasurement_Only_Measurement { get; set; }
	
	}
}