///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#SensingFunction")]
    public interface ISensingFunction  : IFunction
    {
	  ///<summary> function AddHassensingrange_Some_Measurement</summary>  
	  ///<param name="IMeasurement"></param>
      [Collection("https://w3id.org/saref#hasSensingRange")]
	  ICollection<IMeasurement> AddHassensingrange_Some_Measurement { get; set; }
	
	  ///<summary> function AddHassensortype_Only_Property</summary>  
	  ///<param name="IProperty"></param>
      [Collection("https://w3id.org/saref#hasSensorType")]
	  ICollection<IProperty> AddHassensortype_Only_Property { get; set; }
	
	  ///<summary> function AddHascommand_Only_GetSensingDataCommand</summary>  
	  ///<param name="IGetSensingDataCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IGetSensingDataCommand> AddHascommand_Only_GetSensingDataCommand { get; set; }
	
	}
}