///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#Service")]
    public interface IService : IEntity
    {
	  ///<summary> function AddIsofferedby_Min_1Device</summary>  
	  ///<param name="IDevice"></param>
      [Collection("https://w3id.org/saref#isOfferedBy")]
	  ICollection<IDevice> AddIsofferedby_Min_1Device { get; set; }
	
	  ///<summary> function AddRepresents_Min_1Function</summary>  
	  ///<param name="IFunction"></param>
      [Collection("https://w3id.org/saref#represents")]
	  ICollection<IFunction> AddRepresents_Min_1Function { get; set; }
	
	}
}