///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#StartStopFunction")]
    public interface IStartStopFunction  : IActuatingFunction
    {
	  ///<summary> function AddHascommand_Only_StartCommand</summary>  
	  ///<param name="IStartCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IStartCommand> AddHascommand_Only_StartCommand { get; set; }
	
	  ///<summary> function AddHascommand_Only_StopCommand</summary>  
	  ///<param name="IStopCommand"></param>
      [Collection("https://w3id.org/saref#hasCommand")]
	  ICollection<IStopCommand> AddHascommand_Only_StopCommand { get; set; }
	
	}
}