///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#StepUpCommand")]
    public interface IStepUpCommand  : ICommand
    {
	  ///<summary> function AddActsupon_Only_MultiLevelState</summary>  
	  ///<param name="IMultiLevelState"></param>
      [Collection("https://w3id.org/saref#actsUpon")]
	  ICollection<IMultiLevelState> AddActsupon_Only_MultiLevelState { get; set; }
	
	}
}