///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
using www.w3.org.time;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#Time")]
    public interface ITime  : IProperty
    {
	  ///<summary> function AddConsistsof_Some_TemporalEntity</summary>  
	  ///<param name="ITemporalEntity"></param>
      [Collection("https://w3id.org/saref#consistsOf")]
	  ICollection<ITemporalEntity> AddConsistsof_Some_TemporalEntity { get; set; }
	
	}
}