///<summary> 
/// This file is automatically generated by OLGA
/// author OLGA
/// version 1.0 
///</summary> 

using RomanticWeb.Entities;
using RomanticWeb.Mapping.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Reflection;
using static System.Net.WebRequestMethods;

using w3id.org.saref;  
namespace w3id.org.saref
{
    [Class("https://w3id.org/saref#WashingMachine")]
    public interface IWashingMachine  : IAppliance ,ILoad
    {
	  ///<summary> function AddHasfunction_Some_StartStopFunction</summary>  
	  ///<param name="IStartStopFunction"></param>
      [Collection("https://w3id.org/saref#hasFunction")]
	  ICollection<IStartStopFunction> AddHasfunction_Some_StartStopFunction { get; set; }
	
	  ///<summary> function AddHasstate_Some_StartStopState</summary>  
	  ///<param name="IStartStopState"></param>
      [Collection("https://w3id.org/saref#hasState")]
	  ICollection<IStartStopState> AddHasstate_Some_StartStopState { get; set; }
	
	  ///<summary> function AddHasprofile_Some_Profile</summary>  
	  ///<param name="IProfile"></param>
      [Collection("https://w3id.org/saref#hasProfile")]
	  ICollection<IProfile> AddHasprofile_Some_Profile { get; set; }
	
	}
}