/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import w3id.org.saref.IDevice;  
import w3id.org.saref.ITask;

import saref.jsonld.util.RefId;

public class Cleaning implements ITask {

	Map<String, List<RefId>> relations;
	
	public Cleaning(String id) {
		super();
		this.id = "https://w3id.org/saref#" + "Cleaning";
		relations = new HashMap<String, List<RefId>>();
		isAccomplishedByMinDevice = new ArrayList<>();
		
	}

	@JsonldId
	public String id;
	
	@JsonIgnore
	public RefId getRefId()
	{
		return new RefId(id);
	}
	
	@JsonInclude(Include.NON_NULL)
	@JsonProperty("@type")
	public String getType()
	{
		return "https://w3id.org/saref#Task";
	}
	
	
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#isAccomplishedBy") 
	private List<RefId> isAccomplishedByMinDevice;
	public void addisAccomplishedByMin1(IDevice parameter)
	{
		isAccomplishedByMinDevice.add(parameter.getRefId());
	}
			
	
	
	
	
	@JsonInclude(Include.NON_EMPTY)
	@JsonProperty("https://w3id.org/saref#isAccomplishedBy")
	public List<RefId> getisAccomplishedByDevice()
	{
		return isAccomplishedByMinDevice;
	}
	
}