/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import w3id.org.saref.IService;  
import w3id.org.saref.IDevice;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.IPower;  
import w3id.org.saref.IEnergy;  
import w3id.org.saref.ITask;  
import w3id.org.saref.IState;  
import w3id.org.saref.IMeasurement;  
import w3id.org.saref.ICommodity;  
import w3id.org.saref.IFunction;  
import w3id.org.saref.IProfile;  


public interface IDevice  {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	/**
	* addoffersOnly
	* @param IService
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#offers") 
	public void addoffersOnly(IService parameter);
			
	/**
	* addconsistsOfOnly
	* @param IDevice
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#consistsOf") 
	public void addconsistsOfOnly(IDevice parameter);
			
	/**
	* addmeasuresPropertyOnly
	* @param IProperty
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#measuresProperty") 
	public void addmeasuresPropertyOnly(IProperty parameter);
			
	/**
	* addhasTypicalConsumptionOnly
	* @param IPower
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasTypicalConsumption") 
	public void addhasTypicalConsumptionOnly(IPower parameter);
	/**
	* addhasTypicalConsumptionOnly
	* @param IEnergy
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasTypicalConsumption") 
	public void addhasTypicalConsumptionOnly(IEnergy parameter);
			
	/**
	* addaccomplishesMin1
	* @param ITask
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#accomplishes") 
	public void addaccomplishesMin1(ITask parameter);
			
	/**
	* addcontrolsPropertyOnly
	* @param IProperty
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#controlsProperty") 
	public void addcontrolsPropertyOnly(IProperty parameter);
			
	/**
	* addhasStateOnly
	* @param IState
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasState") 
	public void addhasStateOnly(IState parameter);
			
	/**
	* addmakesMeasurementOnly
	* @param IMeasurement
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#makesMeasurement") 
	public void addmakesMeasurementOnly(IMeasurement parameter);
			
	/**
	* addisUsedForOnly
	* @param ICommodity
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#isUsedFor") 
	public void addisUsedForOnly(ICommodity parameter);
			
	/**
	* addhasFunctionMin1
	* @param IFunction
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasFunction") 
	public void addhasFunctionMin1(IFunction parameter);
			
	/**
	* addhasProfileOnly
	* @param IProfile
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasProfile") 
	public void addhasProfileOnly(IProfile parameter);
			
	
}
