/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import w3id.org.saref.ISwitch;  
import w3id.org.saref.IOnOffFunction;  
import w3id.org.saref.ISwitch;  
import w3id.org.saref.IOnOffState;  
import w3id.org.saref.ILight;  
import w3id.org.saref.ISwitchOnService;  


public interface ILightSwitch extends ISwitch {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	/**
	* addhasFunctionSome
	* @param IOnOffFunction
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasFunction") 
	public void addhasFunctionSome(IOnOffFunction parameter);
			
	/**
	* addconsistsOfSome
	* @param ISwitch
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#consistsOf") 
	public void addconsistsOfSome(ISwitch parameter);
			
	/**
	* addhasStateSome
	* @param IOnOffState
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasState") 
	public void addhasStateSome(IOnOffState parameter);
			
	/**
	* addmeasuresPropertySome
	* @param ILight
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#measuresProperty") 
	public void addmeasuresPropertySome(ILight parameter);
			
	/**
	* addoffersSome
	* @param ISwitchOnService
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#offers") 
	public void addoffersSome(ISwitchOnService parameter);
			
			
	
}
