/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import w3id.org.saref.IFunction;  
import w3id.org.saref.IGetCurrentMeterValueCommand;  
import w3id.org.saref.IGetMeterDataCommand;  
import w3id.org.saref.IGetMeterHistoryCommand;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.ICommodity;  
import w3id.org.saref.IMeasurement;  


public interface IMeteringFunction extends IFunction {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	/**
	* addhasCommandOnly
	* @param IGetCurrentMeterValueCommand
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasCommand") 
	public void addhasCommandOnly(IGetCurrentMeterValueCommand parameter);
	/**
	* addhasCommandOnly
	* @param IGetMeterDataCommand
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasCommand") 
	public void addhasCommandOnly(IGetMeterDataCommand parameter);
	/**
	* addhasCommandOnly
	* @param IGetMeterHistoryCommand
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasCommand") 
	public void addhasCommandOnly(IGetMeterHistoryCommand parameter);
			
	/**
	* addhasMeterReadingTypeOnly
	* @param IProperty
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasMeterReadingType") 
	public void addhasMeterReadingTypeOnly(IProperty parameter);
	/**
	* addhasMeterReadingTypeOnly
	* @param ICommodity
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasMeterReadingType") 
	public void addhasMeterReadingTypeOnly(ICommodity parameter);
			
	/**
	* addhasMeterReadingOnly
	* @param IMeasurement
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasMeterReading") 
	public void addhasMeterReadingOnly(IMeasurement parameter);
			
	
}
