/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import w3id.org.saref.IDevice;  
import w3id.org.saref.IMeasurement;  


public interface IProperty  {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	/**
	* addisMeasuredByDeviceOnly
	* @param IDevice
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#isMeasuredByDevice") 
	public void addisMeasuredByDeviceOnly(IDevice parameter);
			
	/**
	* addisControlledByDeviceOnly
	* @param IDevice
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#isControlledByDevice") 
	public void addisControlledByDeviceOnly(IDevice parameter);
			
	/**
	* addrelatesToMeasurementOnly
	* @param IMeasurement
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#relatesToMeasurement") 
	public void addrelatesToMeasurementOnly(IMeasurement parameter);
			
	
}
