/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import w3id.org.saref.IFunction;  
import w3id.org.saref.IMeasurement;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.IGetSensingDataCommand;  


public interface ISensingFunction extends IFunction {

	/**
	* @return RefId
	*/
	@JsonIgnore
	public RefId getRefId();
	
	/**
	* addhasSensingRangeSome
	* @param IMeasurement
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasSensingRange") 
	public void addhasSensingRangeSome(IMeasurement parameter);
			
	/**
	* addhasSensorTypeOnly
	* @param IProperty
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasSensorType") 
	public void addhasSensorTypeOnly(IProperty parameter);
			
	/**
	* addhasCommandOnly
	* @param IGetSensingDataCommand
	*/		
	@JsonInclude(Include.NON_EMPTY)
	@JsonldProperty("https://w3id.org/saref#hasCommand") 
	public void addhasCommandOnly(IGetSensingDataCommand parameter);
			
	
}
