/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import w3id.org.saref.UnitOfMeasure;



import www.wurvoc.org.vocabularies.om_1_8.degree_Celsius.degree_Celsius;
import www.wurvoc.org.vocabularies.om_1_8.kelvin.kelvin;
import www.wurvoc.org.vocabularies.om_1_8.degree_Fahrenheit.degree_Fahrenheit;



public  class TemperatureUnit implements ITemperatureUnit {

	Map<String, List<RefId>> relations;
	
	public TemperatureUnit(String id) {
		super();
		this.id = "https://w3id.org/saref#" + id;
		relations = new HashMap<String, List<RefId>>();
		degree_Celsius degree_celsius = new degree_Celsius("degree_Celsius");
		kelvin kelvin = new kelvin("kelvin");
		degree_Fahrenheit degree_fahrenheit = new degree_Fahrenheit("degree_Fahrenheit");
		
	}

	@JsonldId
	public String id;
	
	@JsonIgnore
	public RefId getRefId()
	{
		return new RefId(id);
	}
	
	@JsonInclude(Include.NON_NULL)
	@JsonProperty("@type")
	public String getType()
	{
		return "https://w3id.org/saref#TemperatureUnit";
	}
	
	
	
	
	
	
}
