/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.ICommand;  
import w3id.org.saref.IOpenCloseState;  


public interface ICloseCommand extends ICommand {


	public IRI iri();
			
	public void addActsupon_Only(IOpenCloseState parameter);
			
	
}
