/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IService;  
import w3id.org.saref.IDevice;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.IPower;  
import w3id.org.saref.IEnergy;  
import w3id.org.saref.ITask;  
import w3id.org.saref.IState;  
import w3id.org.saref.IMeasurement;  
import w3id.org.saref.ICommodity;  
import w3id.org.saref.IFunction;  
import w3id.org.saref.IProfile;  


public interface IDevice  {


	public IRI iri();
			
	public void addOffers_Only(IService parameter);
			
	public void addConsistsof_Only(IDevice parameter);
			
	public void addMeasuresproperty_Only(IProperty parameter);
			
	public void addHastypicalconsumption_Only(IPower parameter);
	public void addHastypicalconsumption_Only(IEnergy parameter);
			
	public void addAccomplishes_Min1(ITask parameter);
			
	public void addControlsproperty_Only(IProperty parameter);
			
	public void addHasstate_Only(IState parameter);
			
	public void addMakesmeasurement_Only(IMeasurement parameter);
			
	public void addIsusedfor_Only(ICommodity parameter);
			
	public void addHasfunction_Min1(IFunction parameter);
			
	public void addHasprofile_Only(IProfile parameter);
			
	
}
