/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.ISwitch;  
import w3id.org.saref.IOpenCloseFunction;  
import w3id.org.saref.IOpenCloseState;  


public interface IDoorSwitch extends ISwitch {


	public IRI iri();
			
	public void addHasfunction_Some(IOpenCloseFunction parameter);
			
	public void addHasstate_Some(IOpenCloseState parameter);
			
	public void addConsistsof_Some(ISwitch parameter);
			
	
}
