/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IMeter;  
import w3id.org.saref.IEnergy;  


public interface IEnergyMeter extends IMeter {


	public IRI iri();
			
	public void addMeasuresproperty_Some(IEnergy parameter);
			
	public void addConsistsof_Some(IMeter parameter);
			
	
}
