/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IFunction;  
import w3id.org.saref.INotifyCommand;  
import w3id.org.saref.IMeasurement;  


public interface IEventFunction extends IFunction {


	public IRI iri();
			
	public void addHascommand_Only(INotifyCommand parameter);
			
	public void addHasthresholdmeasurement_Min1(IMeasurement parameter);
			
	
}
