/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.ISwitch;  
import w3id.org.saref.IOnOffFunction;  
import w3id.org.saref.ISwitch;  
import w3id.org.saref.IOnOffState;  
import w3id.org.saref.ILight;  
import w3id.org.saref.ISwitchOnService;  


public interface ILightSwitch extends ISwitch {


	public IRI iri();
			
	public void addHasfunction_Some(IOnOffFunction parameter);
			
	public void addConsistsof_Some(ISwitch parameter);
			
	public void addHasstate_Some(IOnOffState parameter);
			
	public void addMeasuresproperty_Some(ILight parameter);
			
	public void addOffers_Some(ISwitchOnService parameter);
			
	
}
