/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IUnitOfMeasure;  
import w3id.org.saref.IProperty;  


public interface IMeasurement  {


	public IRI iri();
			
	public void addIsmeasuredin_Exactly1(IUnitOfMeasure parameter);
			
	public void addIsmeasuredin_Only(IUnitOfMeasure parameter);
			
	public void addRelatestoproperty_Exactly1(IProperty parameter);
			
	public void addRelatestoproperty_Only(IProperty parameter);
			
	
}
