/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IFunction;  
import w3id.org.saref.IGetCurrentMeterValueCommand;  
import w3id.org.saref.IGetMeterDataCommand;  
import w3id.org.saref.IGetMeterHistoryCommand;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.ICommodity;  
import w3id.org.saref.IMeasurement;  


public interface IMeteringFunction extends IFunction {


	public IRI iri();
			
	public void addHascommand_Only(IGetCurrentMeterValueCommand parameter);
	public void addHascommand_Only(IGetMeterDataCommand parameter);
	public void addHascommand_Only(IGetMeterHistoryCommand parameter);
			
	public void addHasmeterreadingtype_Only(IProperty parameter);
	public void addHasmeterreadingtype_Only(ICommodity parameter);
			
	public void addHasmeterreading_Only(IMeasurement parameter);
			
	
}
