/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IDevice;  
import w3id.org.saref.IMeasurement;  


public interface IProperty  {


	public IRI iri();
			
	public void addIsmeasuredbydevice_Only(IDevice parameter);
			
	public void addIscontrolledbydevice_Only(IDevice parameter);
			
	public void addRelatestomeasurement_Only(IMeasurement parameter);
			
	
}
