/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.ITime;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.ICommodity;  
import w3id.org.saref.IPrice;  
import w3id.org.saref.IProfile;  


public interface IProfile  {


	public IRI iri();
			
	public void addHastime_Only(ITime parameter);
			
	public void addIsabout_Only(IProperty parameter);
	public void addIsabout_Only(ICommodity parameter);
			
	public void addHasprice_Only(IPrice parameter);
			
	public void addConsistsof_Only(IProfile parameter);
			
	
}
