/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IFunction;  
import w3id.org.saref.IMeasurement;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.IGetSensingDataCommand;  


public interface ISensingFunction extends IFunction {


	public IRI iri();
			
	public void addHassensingrange_Some(IMeasurement parameter);
			
	public void addHassensortype_Only(IProperty parameter);
			
	public void addHascommand_Only(IGetSensingDataCommand parameter);
			
	
}
