/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IDevice;  
import w3id.org.saref.IFunction;  


public interface IService  {


	public IRI iri();
			
	public void addIsofferedby_Min1(IDevice parameter);
			
	public void addRepresents_Min1(IFunction parameter);
			
	
}
