/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IService;  
import w3id.org.saref.IOnOffFunction;  
import w3id.org.saref.ILightSwitch;  


public interface ISwitchOnService extends IService {


	public IRI iri();
			
	public void addRepresents_Some(IOnOffFunction parameter);
			
	public void addIsofferedby_Some(ILightSwitch parameter);
			
	
}
