/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.ISensor;  
import w3id.org.saref.ISensingFunction;  
import w3id.org.saref.ITemperature;  


public interface ITemperatureSensor extends ISensor {


	public IRI iri();
			
	public void addHasfunction_Some(ISensingFunction parameter);
			
	public void addMeasuresproperty_Some(ITemperature parameter);
			
	public void addConsistsof_Some(ISensor parameter);
			
	
}
