/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package w3id.org.saref;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import w3id.org.saref.IAppliance;  
import w3id.org.saref.ILoad;  
import w3id.org.saref.IStartStopFunction;  
import w3id.org.saref.IStartStopState;  
import w3id.org.saref.IProfile;  


public interface IWashingMachine extends IAppliance, ILoad {


	public IRI iri();
			
	public void addHasfunction_Some(IStartStopFunction parameter);
			
	public void addHasstate_Some(IStartStopState parameter);
			
	public void addHasprofile_Some(IProfile parameter);
			
	
}
