/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package w3id.org.saref;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import w3id.org.saref.IGetCurrentMeterValueCommand;  
import w3id.org.saref.IGetMeterDataCommand;  
import w3id.org.saref.IGetMeterHistoryCommand;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.ICommodity;  
import w3id.org.saref.IMeasurement;  
import w3id.org.saref.Function;
import w3id.org.saref.ICommand;
	


public  class MeteringFunction implements IMeteringFunction {

	IRI newInstance;
	
	public MeteringFunction(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("https://w3id.org/saref#MeteringFunction"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	public void addHascommand_Only(IGetCurrentMeterValueCommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
	public void addHascommand_Only(IGetMeterDataCommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
	public void addHascommand_Only(IGetMeterHistoryCommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
	public void addHasmeterreadingtype_Only(IProperty parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasMeterReadingType"), parameter.iri());
	}
	public void addHasmeterreadingtype_Only(ICommodity parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasMeterReadingType"), parameter.iri());
	}
	public void addHasmeterreading_Only(IMeasurement parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasMeterReading"), parameter.iri());
	}
	
	public void addHascommand_Min1(ICommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
			
}
