/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package w3id.org.saref;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import w3id.org.saref.ICloseCommand;  
import w3id.org.saref.IOpenCommand;  
import w3id.org.saref.ActuatingFunction;
import w3id.org.saref.Function;
import w3id.org.saref.ICommand;
	


public  class OpenCloseFunction implements IOpenCloseFunction {

	IRI newInstance;
	
	public OpenCloseFunction(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("https://w3id.org/saref#OpenCloseFunction"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	public void addHascommand_Only(ICloseCommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
	public void addHascommand_Only(IOpenCommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
	
	public void addHascommand_Min1(ICommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
			
}
