/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package w3id.org.saref;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import w3id.org.saref.IMeasurement;  
import w3id.org.saref.IProperty;  
import w3id.org.saref.IGetSensingDataCommand;  
import w3id.org.saref.Function;
import w3id.org.saref.ICommand;
	


public  class SensingFunction implements ISensingFunction {

	IRI newInstance;
	
	public SensingFunction(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("https://w3id.org/saref#SensingFunction"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	public void addHassensingrange_Some(IMeasurement parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasSensingRange"), parameter.iri());
	}
	public void addHassensortype_Only(IProperty parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasSensorType"), parameter.iri());
	}
	public void addHascommand_Only(IGetSensingDataCommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
	
	public void addHascommand_Min1(ICommand parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#hasCommand"), parameter.iri());
	}
			
}
