/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package w3id.org.saref;

import saref.global.util.GLOBAL;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;

import java.math.BigDecimal;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


import w3id.org.saref.IOnOffFunction;  
import w3id.org.saref.ILightSwitch;  
import w3id.org.saref.Service;
import w3id.org.saref.IDevice;
import w3id.org.saref.IFunction;
	


public  class SwitchOnService implements ISwitchOnService {

	IRI newInstance;
	
	public SwitchOnService(String namespace, String instanceId) {
		super();
		newInstance = GLOBAL.factory.createIRI(namespace, instanceId);
		GLOBAL.model.add(newInstance, RDF.TYPE, GLOBAL.factory.createIRI("https://w3id.org/saref#SwitchOnService"));
	}

	public IRI iri()
	{
		return newInstance;
	}

	
	public void addRepresents_Some(IOnOffFunction parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#represents"), parameter.iri());
	}
	public void addIsofferedby_Some(ILightSwitch parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#isOfferedBy"), parameter.iri());
	}
	
	public void addIsofferedby_Min1(IDevice parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#isOfferedBy"), parameter.iri());
	}
			
	public void addRepresents_Min1(IFunction parameter)
	{
		GLOBAL.model.add(newInstance, GLOBAL.factory.createIRI("https://w3id.org/saref#represents"), parameter.iri());
	}
			
}
