/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package saref.global.util;

import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.ValueFactory;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.model.impl.TreeModel;


public class GLOBAL {

	public static Model model = new TreeModel();
	public static ValueFactory factory = SimpleValueFactory.getInstance();
}