/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/

package www.w3.org.owl;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.RDF;



public interface IThing  {


	public IRI iri();
			
	
}
