/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package www.w3.org._2006.time;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import www.w3.org._2002._07.owl.Thing;



import www.w3.org._2006.time.Friday;
import www.w3.org._2006.time.Sunday;
import www.w3.org._2006.time.Saturday;
import www.w3.org._2006.time.Thursday;
import www.w3.org._2006.time.Tuesday;
import www.w3.org._2006.time.Wednesday;
import www.w3.org._2006.time.Monday;



public  class DayOfWeek implements IDayOfWeek {

	Map<String, List<RefId>> relations;
	
	public DayOfWeek(String id) {
		super();
		this.id = "http://www.w3.org/2006/time#" + id;
		relations = new HashMap<String, List<RefId>>();
		Friday friday = new Friday("Friday");
		Sunday sunday = new Sunday("Sunday");
		Saturday saturday = new Saturday("Saturday");
		Thursday thursday = new Thursday("Thursday");
		Tuesday tuesday = new Tuesday("Tuesday");
		Wednesday wednesday = new Wednesday("Wednesday");
		Monday monday = new Monday("Monday");
		
	}

	@JsonldId
	public String id;
	
	@JsonIgnore
	public RefId getRefId()
	{
		return new RefId(id);
	}
	
	@JsonInclude(Include.NON_NULL)
	@JsonProperty("@type")
	public String getType()
	{
		return "http://www.w3.org/2006/time#DayOfWeek";
	}
	
	
	
	
	
	
}
