/**
* This file is automatically generated by OLGA
* @author OLGA
* @version 1.0
*/
package www.w3.org._2006.time;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldId;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldProperty;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldType;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldLink;
import ioinformarics.oss.jackson.module.jsonld.annotation.JsonldPropertyType;

import saref.jsonld.util.RefId;

import www.w3.org._2006.time.TemporalDuration;
import w3id.org.saref.UnitOfMeasure;



import www.w3.org._2006.time.unitSecond;
import www.w3.org._2006.time.unitHour;
import www.w3.org._2006.time.unitMonth;
import www.w3.org._2006.time.unitDay;
import www.w3.org._2006.time.unitMinute;
import www.w3.org._2006.time.unitWeek;
import www.w3.org._2006.time.unitYear;



public  class TemporalUnit implements ITemporalUnit {

	Map<String, List<RefId>> relations;
	
	public TemporalUnit(String id) {
		super();
		this.id = "http://www.w3.org/2006/time#" + id;
		relations = new HashMap<String, List<RefId>>();
		unitSecond unitsecond = new unitSecond("unitSecond");
		unitHour unithour = new unitHour("unitHour");
		unitMonth unitmonth = new unitMonth("unitMonth");
		unitDay unitday = new unitDay("unitDay");
		unitMinute unitminute = new unitMinute("unitMinute");
		unitWeek unitweek = new unitWeek("unitWeek");
		unitYear unityear = new unitYear("unitYear");
		
	}

	@JsonldId
	public String id;
	
	@JsonIgnore
	public RefId getRefId()
	{
		return new RefId(id);
	}
	
	@JsonInclude(Include.NON_NULL)
	@JsonProperty("@type")
	public String getType()
	{
		return "http://www.w3.org/2006/time#TemporalUnit";
	}
	
	
	
	
	
	
}
